ARG BALENA_MACHINE_NAME_ARG=%%BALENA_MACHINE_NAME%%

FROM balenalib/$BALENA_MACHINE_NAME_ARG-alpine:run

RUN curl https://getcaddy.com | bash

COPY init.sh /init.sh
RUN chmod +x /init.sh

ENTRYPOINT ["/init.sh"]
